/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.rental.film.operator;

import java.awt.event.ActionListener;

/**
 *
 * @author  usu
 */
public class MenuUtama extends javax.swing.JPanel {

    private static final long serialVersionUID = -1;

    /** Creates new form MenuUtama */
    public MenuUtama() {
        initComponents();
    }

    public void addActionListenerAnggota(ActionListener l) {
        buttonAnggota.addActionListener(l);
    }

    public void addActionListenerFilm(ActionListener l) {
        buttonFilm.addActionListener(l);
    }

    public void addActionListenerPengembalian(ActionListener l) {
        buttonKembalikan.addActionListener(l);
    }

    public void addActionListenerPesan(ActionListener l) {
        buttonPesan.addActionListener(l);
    }

    public void addActionListenerPeminjaman(ActionListener l) {
        buttonPinjam.addActionListener(l);
    }

    public void addActionListenerPribadi(ActionListener l) {
        buttonPribadi.addActionListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonPribadi = new usu.rental.film.widget.ButtonBig();
        buttonFilm = new usu.rental.film.widget.ButtonBig();
        buttonAnggota = new usu.rental.film.widget.ButtonBig();
        buttonPinjam = new usu.rental.film.widget.ButtonBig();
        buttonKembalikan = new usu.rental.film.widget.ButtonBig();
        buttonPesan = new usu.rental.film.widget.ButtonBig();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        buttonPribadi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/operator2.png"))); // NOI18N
        buttonPribadi.setMnemonic('P');
        buttonPribadi.setText("pribadi");
        add(buttonPribadi, new java.awt.GridBagConstraints());

        buttonFilm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/dvd.png"))); // NOI18N
        buttonFilm.setMnemonic('F');
        buttonFilm.setText("film");
        add(buttonFilm, new java.awt.GridBagConstraints());

        buttonAnggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/user.png"))); // NOI18N
        buttonAnggota.setMnemonic('A');
        buttonAnggota.setText("anggota");
        add(buttonAnggota, new java.awt.GridBagConstraints());

        buttonPinjam.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/peminjaman.png"))); // NOI18N
        buttonPinjam.setMnemonic('E');
        buttonPinjam.setText("peminjaman");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(buttonPinjam, gridBagConstraints);

        buttonKembalikan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/pengembalian.png"))); // NOI18N
        buttonKembalikan.setMnemonic('N');
        buttonKembalikan.setText("pengembalian");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(buttonKembalikan, gridBagConstraints);

        buttonPesan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/report.png"))); // NOI18N
        buttonPesan.setMnemonic('S');
        buttonPesan.setText("pesan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(buttonPesan, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.rental.film.widget.ButtonBig buttonAnggota;
    usu.rental.film.widget.ButtonBig buttonFilm;
    usu.rental.film.widget.ButtonBig buttonKembalikan;
    usu.rental.film.widget.ButtonBig buttonPesan;
    usu.rental.film.widget.ButtonBig buttonPinjam;
    usu.rental.film.widget.ButtonBig buttonPribadi;
    // End of variables declaration//GEN-END:variables
}
