/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.rental.film.operator;

import java.awt.event.ActionListener;
import usu.rental.film.data.Setting;
import usu.rental.film.data.exception.DataNotCompleteException;
import usu.rental.film.widget.Table;
import usu.rental.film.widget.TextBox;
import usu.rental.film.widget.table.TableModelFilm;
import usu.rental.film.widget.table.render.DefaultTableCellRender;

/**
 *
 * @author  usu
 */
public class PanelPeminjaman extends javax.swing.JPanel {

    private static final long serialVersionUID = -1;
    private TableModelFilm tableModel;
    private int totalBayar = 0;
    private Setting setting;

    /** Creates new form PanelPeminjaman */
    public PanelPeminjaman() {
        initVariables();
        initComponents();
        initFinal();
    }

    public void addActionListenerBatal(ActionListener l) {
        buttonBatal.addActionListener(l);
    }

    public void addActionListenerLihat(ActionListener l) {
        buttonLihat.addActionListener(l);
        textAnggota.addActionListener(l);
    }

    public void addActionListenerPinjam(ActionListener l) {
        buttonPinjam.addActionListener(l);
    }

    public void addActionListenerTambah(ActionListener l) {
        buttonTambah.addActionListener(l);
        textFilm.addActionListener(l);
    }

    public void addActionListenerHapus(ActionListener l) {
        buttonHapus.addActionListener(l);
    }

    public void setSetting(Setting setting) {
        this.setting = setting;
    }

    public Table getTable() {
        return table;
    }

    public TableModelFilm getTableModel() {
        return tableModel;
    }

    public int getTotalBayar() {
        return totalBayar;
    }

    public void addFilm() {
        totalBayar += setting.getHargaPeminjaman();
        setTitleBayar(totalBayar);
    }

    void removeFilm() {
        totalBayar -= setting.getHargaPeminjaman();
        setTitleBayar(totalBayar);
    }

    void setTitleBayar(int total) {
        labelTotalBayar.setText("Rp." + total);
    }

    public void reset() {
        totalBayar = 0;
        setTitleBayar(totalBayar);
        tableModel.removeAllElements();
        textAnggota.setText("");
        textFilm.setText("");
    }

    public TextBox getTextFilm() {
        return textFilm;
    }

    public String getAnggota() throws DataNotCompleteException {
        if (textAnggota.getText().trim().equals("")) {
            throw new DataNotCompleteException("id anggota masih kosong");
        }
        return textAnggota.getText();
    }

    public String getFilm() throws DataNotCompleteException {
        if (textFilm.getText().trim().equals("")) {
            throw new DataNotCompleteException("id film masih kosong");
        }
        return textFilm.getText();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usu.rental.film.widget.Label label1 = new usu.rental.film.widget.Label();
        textAnggota = new usu.rental.film.widget.TextBox();
        buttonLihat = new usu.rental.film.widget.Button();
        usu.rental.film.widget.Label label2 = new usu.rental.film.widget.Label();
        textFilm = new usu.rental.film.widget.TextBox();
        buttonTambah = new usu.rental.film.widget.Button();
        usu.rental.film.widget.ScrollPane scrollPane1 = new usu.rental.film.widget.ScrollPane();
        table = new usu.rental.film.widget.Table();
        buttonHapus = new usu.rental.film.widget.Button();
        buttonPinjam = new usu.rental.film.widget.Button();
        buttonBatal = new usu.rental.film.widget.Button();
        usu.rental.film.widget.Label label3 = new usu.rental.film.widget.Label();
        labelTotalBayar = new usu.rental.film.widget.Label();

        setOpaque(false);

        label1.setDisplayedMnemonic('I');
        label1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label1.setText("id anggota :");

        textAnggota.setText("anggota");
        textAnggota.setFocusAccelerator('I');

        buttonLihat.setMnemonic('L');
        buttonLihat.setText("lihat");

        label2.setDisplayedMnemonic('F');
        label2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label2.setText("id film :");

        textFilm.setText("film");
        textFilm.setFocusAccelerator('F');

        buttonTambah.setMnemonic('T');
        buttonTambah.setText("tambah");

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrollPane1.setViewportView(table);

        buttonHapus.setMnemonic('H');
        buttonHapus.setText("hapus");

        buttonPinjam.setMnemonic('P');
        buttonPinjam.setText("pinjam");

        buttonBatal.setMnemonic('B');
        buttonBatal.setText("batal");

        label3.setText("total bayar :");

        labelTotalBayar.setText("Rp.0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                            .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(textFilm, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                            .addComponent(textAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 561, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(labelTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 323, Short.MAX_VALUE)
                                .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buttonLihat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                            .addComponent(buttonTambah, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonLihat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonTambah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFilm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonHapus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(label3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.rental.film.widget.Button buttonBatal;
    usu.rental.film.widget.Button buttonHapus;
    usu.rental.film.widget.Button buttonLihat;
    usu.rental.film.widget.Button buttonPinjam;
    usu.rental.film.widget.Button buttonTambah;
    usu.rental.film.widget.Label labelTotalBayar;
    usu.rental.film.widget.Table table;
    usu.rental.film.widget.TextBox textAnggota;
    usu.rental.film.widget.TextBox textFilm;
    // End of variables declaration//GEN-END:variables

    private void initFinal() {
        table.setModel(tableModel);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
    }
    // End of variables declaration

    private void initVariables() {
        tableModel = new TableModelFilm();
    }
}
