/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.rental.film.operator;

import java.awt.event.ActionListener;
import usu.rental.film.data.Setting;
import usu.rental.film.data.exception.DataNotCompleteException;
import usu.rental.film.widget.Table;
import usu.rental.film.widget.table.TableModelPeminjaman;
import usu.rental.film.widget.table.render.DefaultTableCellRender;

/**
 *
 * @author  usu
 */
public class PanelPengembalian extends javax.swing.JPanel {

    private static final long serialVersionUID = -1;
    private TableModelPeminjaman tableModel;
    private Setting setting;

    /** Creates new form PanelPeminjaman */
    public PanelPengembalian() {
        initVariables();
        initComponents();
        initFinal();
    }

    public void setSetting(Setting setting) {
        this.setting = setting;
    }

    public Table getTable() {
        return table;
    }

    public TableModelPeminjaman getTableModel() {
        return tableModel;
    }

    public void addActionListenerCekPeminjaman(ActionListener l) {
        buttonCekPeminjaman.addActionListener(l);
        textAnggota.addActionListener(l);
    }

    public void addActionListenerKembalikanSemua(ActionListener l) {
        buttonKembalikansemua.addActionListener(l);
    }

    public void addActionListenerKembalikan(ActionListener l) {
        buttonkembalikan.addActionListener(l);
    }

    public String getAnggota() throws DataNotCompleteException {
        if (textAnggota.getText().trim().equals("")) {
            throw new DataNotCompleteException("id anggota masih kosong");
        }
        return textAnggota.getText();
    }

    public void reset() {
        textAnggota.setText("");
        tableModel.removeAllElements();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        usu.rental.film.widget.Label label1 = new usu.rental.film.widget.Label();
        textAnggota = new usu.rental.film.widget.TextBox();
        buttonCekPeminjaman = new usu.rental.film.widget.Button();
        usu.rental.film.widget.ScrollPane scrollPane1 = new usu.rental.film.widget.ScrollPane();
        table = new usu.rental.film.widget.Table();
        buttonKembalikansemua = new usu.rental.film.widget.Button();
        buttonkembalikan = new usu.rental.film.widget.Button();

        setOpaque(false);

        label1.setDisplayedMnemonic('I');
        label1.setText("id anggota :");

        textAnggota.setText("anggota");
        textAnggota.setFocusAccelerator('I');

        buttonCekPeminjaman.setMnemonic('C');
        buttonCekPeminjaman.setText("cek peminjaman");

        scrollPane1.setViewportView(table);

        buttonKembalikansemua.setMnemonic('S');
        buttonKembalikansemua.setText("kembalikan semua");

        buttonkembalikan.setMnemonic('K');
        buttonkembalikan.setText("kembalikan");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 630, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(textAnggota, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonCekPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(buttonkembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonKembalikansemua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonCekPeminjaman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonKembalikansemua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonkembalikan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.rental.film.widget.Button buttonCekPeminjaman;
    usu.rental.film.widget.Button buttonKembalikansemua;
    usu.rental.film.widget.Button buttonkembalikan;
    usu.rental.film.widget.Table table;
    usu.rental.film.widget.TextBox textAnggota;
    // End of variables declaration//GEN-END:variables

    private void initFinal() {
        table.setModel(tableModel);

        for (int i = 0; i < table.getColumnCount(); i++) {
            table.getColumnModel().getColumn(i).setCellRenderer(new DefaultTableCellRender());
        }
    }
    // End of variables declaration

    private void initVariables() {
        tableModel = new TableModelPeminjaman();
    }
}
