/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.rental.film.admin;

import java.awt.event.ActionListener;

/**
 *
 * @author  usu
 */
public class MenuLaporan extends javax.swing.JPanel {

    /*
     * Serial version UID
     */
    private static final long serialVersionUID = 1L;

    /** Creates new form MenuLaporan */
    public MenuLaporan() {
        initComponents();
    }

    public void addActionListenerPeminjaman(ActionListener l) {
        peminjaman.addActionListener(l);
    }

    public void addActionListenerPengembalian(ActionListener l) {
        pengembalian.addActionListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        peminjaman = new usu.rental.film.widget.ButtonBig();
        pengembalian = new usu.rental.film.widget.ButtonBig();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        peminjaman.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/peminjaman.png"))); // NOI18N
        peminjaman.setMnemonic('I');
        peminjaman.setText("peminjaman");
        add(peminjaman, new java.awt.GridBagConstraints());

        pengembalian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/pengembalian.png"))); // NOI18N
        pengembalian.setMnemonic('E');
        pengembalian.setText("pengembalian");
        add(pengembalian, new java.awt.GridBagConstraints());
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.rental.film.widget.ButtonBig peminjaman;
    private usu.rental.film.widget.ButtonBig pengembalian;
    // End of variables declaration//GEN-END:variables
}
