/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.rental.film.admin;

import java.awt.event.ActionListener;

/**
 *
 * @author  usu
 */
public class MenuUtama extends javax.swing.JPanel {

    /*
     * Serial version UID
     */
    private static final long serialVersionUID = 1L;

    /** Creates new form MenuUtama */
    public MenuUtama() {
        initComponents();
    }

    public void addActionListenerOperator(ActionListener l) {
        operator.addActionListener(l);
    }

    public void addActionListenerAnggota(ActionListener l) {
        anggota.addActionListener(l);
    }

    public void addActionListenerDatabase(ActionListener l) {
        database.addActionListener(l);
    }

    public void addActionListenerFilm(ActionListener l) {
        film.addActionListener(l);
    }

    public void addActionListenerLaporan(ActionListener l) {
        laporan.addActionListener(l);
    }

    public void addActionListenerPengaturan(ActionListener l) {
        pengaturan.addActionListener(l);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        operator = new usu.rental.film.widget.ButtonBig();
        anggota = new usu.rental.film.widget.ButtonBig();
        film = new usu.rental.film.widget.ButtonBig();
        laporan = new usu.rental.film.widget.ButtonBig();
        pengaturan = new usu.rental.film.widget.ButtonBig();
        database = new usu.rental.film.widget.ButtonBig();

        setOpaque(false);
        setLayout(new java.awt.GridBagLayout());

        operator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/operator2.png"))); // NOI18N
        operator.setMnemonic('O');
        operator.setText("operator");
        add(operator, new java.awt.GridBagConstraints());

        anggota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/user.png"))); // NOI18N
        anggota.setMnemonic('A');
        anggota.setText("anggota");
        add(anggota, new java.awt.GridBagConstraints());

        film.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/dvd.png"))); // NOI18N
        film.setMnemonic('F');
        film.setText("film");
        add(film, new java.awt.GridBagConstraints());

        laporan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/report.png"))); // NOI18N
        laporan.setMnemonic('L');
        laporan.setText("laporan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        add(laporan, gridBagConstraints);

        pengaturan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/setting.png"))); // NOI18N
        pengaturan.setMnemonic('P');
        pengaturan.setText("pengaturan");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        add(pengaturan, gridBagConstraints);

        database.setIcon(new javax.swing.ImageIcon(getClass().getResource("/usu/rental/film/resource/database.png"))); // NOI18N
        database.setMnemonic('D');
        database.setText("database");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        add(database, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private usu.rental.film.widget.ButtonBig anggota;
    private usu.rental.film.widget.ButtonBig database;
    private usu.rental.film.widget.ButtonBig film;
    private usu.rental.film.widget.ButtonBig laporan;
    private usu.rental.film.widget.ButtonBig operator;
    private usu.rental.film.widget.ButtonBig pengaturan;
    // End of variables declaration//GEN-END:variables
}
