/*
 * DILARANG MENGHAPUS ATAU MENGEDIT COPYRIGHT INI.
 * 
 * Copyright 2008 echo.khannedy@gmail.com. 
 * All rights reserved.
 * 
 * Semua isi dalam file ini adalah hak milik dari echo.khannedy@gmail.com
 * Anda tak diperkenankan untuk menggunakan file atau mengubah file
 * ini kecuali anda tidak menghapus atau merubah lisence ini.
 * 
 * File ini dibuat menggunakan :
 * IDE        : NetBeans
 * NoteBook   : Acer Aspire 5920G
 * OS         : Windows Vista
 * Java       : Java 1.6
 * 
 */
package usu.rental.film.admin;

import java.awt.event.ActionListener;
import java.sql.Date;

/**
 *
 * @author  usu
 */
public class PanelSaringOperator extends javax.swing.JPanel {

    /*
     * Serial version UID
     */
    private static final long serialVersionUID = 1L;

    /** Creates new form PanelSaringAnggota */
    public PanelSaringOperator() {
        initComponents();
    }

    public void addActionListenerSaring(ActionListener l) {
        buttonMulaiSaring.addActionListener(l);
    }

    public void addActionListenerBatal(ActionListener l) {
        batalSharing.addActionListener(l);
    }

    public String getId() {
        if (saringId.isEnabled()) {
            return saringId.getText();
        }
        return null;
    }

    public String getNama() {
        if (saringNama.isEnabled()) {
            return saringNama.getText();
        }
        return null;
    }

    public String getKontak() {
        if (saringKontak.isEnabled()) {
            return saringKontak.getText();
        }
        return null;
    }

    public String getAlamat() {
        if (saringAlamat.isEnabled()) {
            return saringAlamat.getText();
        }
        return null;
    }

    public Date getLahirDari() {
        if (saringTanggalDari.isEnabled()) {
            return new Date(((java.util.Date) saringTanggalDari.getValue()).getTime());
        }
        return null;
    }

    public Date getLahirSampai() {
        if (saringTanggalSampai.isEnabled()) {
            return new Date(((java.util.Date) saringTanggalSampai.getValue()).getTime());
        }
        return null;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonMulaiSaring = new usu.rental.film.widget.Button();
        batalSharing = new usu.rental.film.widget.Button();
        usu.widget.glass.PanelGlass panelGlass2 = new usu.widget.glass.PanelGlass();
        usu.rental.film.widget.Label label7 = new usu.rental.film.widget.Label();
        usu.rental.film.widget.Label label8 = new usu.rental.film.widget.Label();
        usu.rental.film.widget.Label label9 = new usu.rental.film.widget.Label();
        usu.rental.film.widget.Label label10 = new usu.rental.film.widget.Label();
        usu.rental.film.widget.Label label11 = new usu.rental.film.widget.Label();
        usu.rental.film.widget.Label label12 = new usu.rental.film.widget.Label();
        saringId = new usu.rental.film.widget.TextBox();
        saringNama = new usu.rental.film.widget.TextBox();
        saringTanggalDari = new usu.rental.film.widget.FormatterBox();
        saringTanggalSampai = new usu.rental.film.widget.FormatterBox();
        saringKontak = new usu.rental.film.widget.TextBox();
        saringAlamat = new usu.rental.film.widget.TextBox();
        javax.swing.JCheckBox jCheckBox1 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox2 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox3 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox4 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox5 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox6 = new javax.swing.JCheckBox();

        setOpaque(false);

        buttonMulaiSaring.setMnemonic('G');
        buttonMulaiSaring.setText("saring");

        batalSharing.setMnemonic('B');
        batalSharing.setText("batal");

        panelGlass2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        panelGlass2.setOpaqueImage(false);
        panelGlass2.setRound(false);

        label7.setDisplayedMnemonic('I');
        label7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label7.setText("id operator :");

        label8.setDisplayedMnemonic('N');
        label8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label8.setText("nama operator :");

        label9.setDisplayedMnemonic('L');
        label9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label9.setText("tanggal lahir operator mulai :");

        label10.setDisplayedMnemonic('O');
        label10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label10.setText("tanggal lahir operator sampai :");

        label11.setDisplayedMnemonic('K');
        label11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label11.setText("kontak operator :");

        label12.setDisplayedMnemonic('A');
        label12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        label12.setText("alamat operator :");

        saringId.setFocusAccelerator('I');
        saringId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saringIdActionPerformed(evt);
            }
        });

        saringNama.setFocusAccelerator('N');
        saringNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saringNamaActionPerformed(evt);
            }
        });

        saringTanggalDari.setFocusAccelerator('L');
        saringTanggalDari.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        saringTanggalDari.setValue(new java.util.Date());
        saringTanggalDari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saringTanggalDariActionPerformed(evt);
            }
        });

        saringTanggalSampai.setFocusAccelerator('O');
        saringTanggalSampai.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(java.text.DateFormat.getDateInstance(java.text.DateFormat.LONG))));
        saringTanggalSampai.setValue(new java.util.Date());
        saringTanggalSampai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saringTanggalSampaiActionPerformed(evt);
            }
        });

        saringKontak.setFocusAccelerator('K');
        saringKontak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saringKontakActionPerformed(evt);
            }
        });

        saringAlamat.setFocusAccelerator('A');
        saringAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saringAlamatActionPerformed(evt);
            }
        });

        jCheckBox1.setFocusable(false);
        jCheckBox1.setOpaque(false);

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, saringId, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jCheckBox1, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBox2.setFocusable(false);
        jCheckBox2.setOpaque(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, saringNama, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jCheckBox2, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBox3.setFocusable(false);
        jCheckBox3.setOpaque(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, saringTanggalDari, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jCheckBox3, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBox4.setFocusable(false);
        jCheckBox4.setOpaque(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, saringTanggalSampai, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jCheckBox4, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBox5.setFocusable(false);
        jCheckBox5.setOpaque(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, saringKontak, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jCheckBox5, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        jCheckBox6.setFocusable(false);
        jCheckBox6.setOpaque(false);

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, saringAlamat, org.jdesktop.beansbinding.ELProperty.create("${enabled}"), jCheckBox6, org.jdesktop.beansbinding.BeanProperty.create("selected"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout panelGlass2Layout = new javax.swing.GroupLayout(panelGlass2);
        panelGlass2.setLayout(panelGlass2Layout);
        panelGlass2Layout.setHorizontalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(label10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(saringAlamat, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(saringKontak, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(saringId, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(saringNama, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(saringTanggalDari, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                    .addComponent(saringTanggalSampai, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jCheckBox2)
                    .addComponent(jCheckBox3)
                    .addComponent(jCheckBox4)
                    .addComponent(jCheckBox5)
                    .addComponent(jCheckBox6))
                .addContainerGap())
        );
        panelGlass2Layout.setVerticalGroup(
            panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelGlass2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saringId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saringNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saringTanggalDari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saringTanggalSampai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saringKontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelGlass2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saringAlamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelGlass2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(batalSharing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonMulaiSaring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelGlass2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonMulaiSaring, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(batalSharing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(180, Short.MAX_VALUE))
        );

        bindingGroup.bind();
    }// </editor-fold>//GEN-END:initComponents

private void saringIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saringIdActionPerformed
    saringNama.requestFocusInWindow();
}//GEN-LAST:event_saringIdActionPerformed

private void saringNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saringNamaActionPerformed
    saringTanggalDari.requestFocusInWindow();
}//GEN-LAST:event_saringNamaActionPerformed

private void saringTanggalDariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saringTanggalDariActionPerformed
    saringTanggalSampai.requestFocusInWindow();
}//GEN-LAST:event_saringTanggalDariActionPerformed

private void saringTanggalSampaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saringTanggalSampaiActionPerformed
    saringKontak.requestFocusInWindow();
}//GEN-LAST:event_saringTanggalSampaiActionPerformed

private void saringKontakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saringKontakActionPerformed
    saringAlamat.requestFocusInWindow();
}//GEN-LAST:event_saringKontakActionPerformed

private void saringAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saringAlamatActionPerformed
    buttonMulaiSaring.requestFocusInWindow();
}//GEN-LAST:event_saringAlamatActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    usu.rental.film.widget.Button batalSharing;
    usu.rental.film.widget.Button buttonMulaiSaring;
    usu.rental.film.widget.TextBox saringAlamat;
    usu.rental.film.widget.TextBox saringId;
    usu.rental.film.widget.TextBox saringKontak;
    usu.rental.film.widget.TextBox saringNama;
    usu.rental.film.widget.FormatterBox saringTanggalDari;
    usu.rental.film.widget.FormatterBox saringTanggalSampai;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables
}
